### ISSUE TITLE
add new features to extension.

### ISSUE THREAD

**Issue by DH3ALEJANDRO** [demonmhon/brackets-working-file-tabs#3]
Hi :)

I have developed an interactive way to play with the sidebar, I would like to implement it on your extension.

``` javascript
define(function (require, exports, module) {
    'use strict';
    var AppInit            = brackets.getModule('utils/AppInit'),
        Resizer            = brackets.getModule('utils/Resizer'),
        SidebarView        = brackets.getModule('project/SidebarView'),
        ExtensionUtils     = brackets.getModule("utils/ExtensionUtils"),
        $sidebar           = $("#sidebar");
    function startOp() {
        Resizer.toggle($sidebar);
    }
    var tabContainer = $( '<div>', {
        'id':    'working-file-tabs-container',
        'class': 'working-file-tabs-container end-left'
    } );
    function addButton() {
        var $newdiv1 = $( "<div>", {
            'id': 'fullScreenSidebar',
            'class': 'btn-sidebar-bks btn-alt-quiet'
        } ).click( startOp );
        $('#working-file-tabs-scroll-container').after($newdiv1);
    }
    function addHTML(){
        var $sideView = $('#fullScreenSidebar');
        if(SidebarView.isVisible()){
            $sideView.html('←').attr('title', 'Hide Sidebar').css('color', '#37b1ac');
        } else {
            $sideView.html('→').attr('title', 'Show Sidebar');
        }
        $sidebar.on("panelCollapsed", function(){
            $sideView.html('→').attr('title', 'Show Sidebar');
            if($sideView.css('color')){$sideView.removeAttr('style');}
        });
        $sidebar.on("panelExpanded",  function(){
            $sideView.html('←').attr('title', 'Hide Sidebar').css('color', '#37b1ac');
        });
    }
    function panelToggle(){
        ExtensionUtils.loadStyleSheet(module, "style.css");
        addButton();
        addHTML();
    }
    AppInit.appReady(function () {
        panelToggle();
    });
});
```

and file "style.css".
```css
.btn-sidebar-bks{
    position: absolute;
    left: 4px;
    top: 4px;
    opacity: 0.7;
    z-index: 1;
    color: #A1AFB3;
    padding: 3px 4px;
    font-size: 14px;
    font-family: 'Times New Roman';
    font-weight: bold;
    line-height: 14px;
}
.working-file-tabs-container .working-file-tabs-scroll-container {
    margin-left: 86px;
}
.open-files-container{
    overflow-y: hidden!important;
}
.working-file-tabs-container .working-set-option-btn {
    left: 58px;
}
.working-file-tabs-container .working-set-splitview-btn {
    left: 31px;
}
```

showing preview.

![showing preview](http://www.mediafire.com/convkey/6f80/o6yfh41c315w4nnzg.jpg?size_id=3)
